<a href="https://colab.research.google.com/github/ParnianH98/Local-search-on-8-queen/blob/main/genetic_algorithm_8_queen.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import random
import math
population = 100

get a filtered-arbitrary initial state of 8-queen from the user

In [ ]:
L = []


for i in range(population):
  Ls = []
  for j in range(8):
    a = random.randint(0,7)
    Ls.append(a)
  L.append(Ls)

mat = np.zeros((8,8))
print(L)


[[0, 0, 7, 4, 6, 1, 1, 1], [1, 3, 4, 7, 0, 4, 3, 6], [4, 4, 4, 2, 4, 6, 1, 2], [7, 0, 7, 5, 7, 2, 3, 3], [1, 5, 7, 1, 2, 6, 0, 0], [1, 3, 0, 5, 3, 6, 0, 4], [1, 1, 1, 7, 6, 2, 4, 7], [4, 0, 4, 0, 3, 1, 0, 7], [7, 2, 1, 0, 0, 7, 4, 2], [6, 2, 1, 2, 6, 2, 0, 6], [2, 6, 4, 1, 6, 4, 2, 7], [5, 3, 1, 4, 4, 0, 7, 4], [7, 5, 5, 2, 1, 7, 6, 5], [4, 6, 3, 4, 4, 5, 0, 7], [7, 0, 6, 6, 0, 0, 0, 3], [5, 7, 5, 5, 6, 6, 2, 4], [0, 5, 6, 1, 0, 5, 3, 1], [3, 3, 7, 5, 0, 1, 0, 7], [1, 5, 6, 6, 7, 1, 7, 3], [5, 3, 4, 5, 1, 7, 7, 2], [7, 2, 2, 4, 2, 7, 3, 3], [1, 0, 3, 1, 4, 5, 0, 1], [4, 3, 0, 1, 2, 4, 4, 1], [3, 3, 0, 2, 5, 6, 7, 4], [5, 0, 5, 4, 0, 5, 7, 1], [4, 1, 5, 6, 5, 3, 0, 3], [2, 3, 0, 4, 6, 6, 3, 5], [4, 2, 2, 7, 3, 4, 5, 2], [0, 2, 0, 4, 7, 3, 2, 4], [7, 1, 7, 4, 1, 6, 1, 4], [4, 3, 0, 5, 7, 2, 0, 7], [1, 2, 6, 1, 0, 7, 0, 1], [5, 4, 5, 1, 1, 1, 7, 5], [6, 1, 4, 0, 2, 1, 5, 7], [7, 5, 0, 0, 4, 0, 0, 1], [2, 6, 0, 1, 0, 3, 3, 5], [4, 5, 2, 6, 7, 4, 1, 0], [6, 7, 4, 1, 5, 2, 3, 2], [7, 6, 5, 7

generate the board matrix from the entered list

In [ ]:
def gen_mat(List):
  matrix = np.zeros((8,8))
  for i in range(8):
    matrix[List[i]][i] = 1
  return matrix

calculate the fittness function for a board: how many queen pairs attack each other

In [ ]:
def fittness_cal(lst):
  attack = 0
  for i in range(8):
    for j in range(i+1,8):
      if lst[i]==lst[j]:
        attack+=1
      elif (i-j == lst[i]-lst[j]) or (j-i == lst[i]-lst[j]):
        attack+=1

  return attack




CrossOver function

In [ ]:
def CrossOver(lst1,lst2):
  pos = random.randint(0,6)
  for i in range(pos+1):
    lst1[i] , lst2[i] = lst2[i] , lst1[i]

  return lst1,lst2

mutate a list

In [ ]:
def mutate(lst):
  rand = random.random()
  if rand < 0.3:
    pos = random.randint(0,7)
    val = random.randint(0,7)

    lst[pos] = val

  return lst

Sort

In [ ]:
def Sort(flst,lst):
  for i in range(len(flst)-1):
    for j in range(i+1,len(flst)):
      if flst[j]<flst[i]:
        flst[i],flst[j] = flst[j],flst[i]
        lst[i],lst[j] = lst[j],lst[i]

  return flst,lst

In [ ]:
def genetic(lst):
  
  for k in range(500):
    fitL = []
    for i in range(population):
      fitL.append(fittness_cal(lst[i]))

    fitL,L = Sort(fitL,lst)
    if fitL[0]==0:
      return fitL,lst

    for i in range(0,population,2):
      lst[i],lst[i+1] = CrossOver(L[i],L[i+1])
    
    for j in range(population):
      lst[j] = mutate(lst[j])

  return fitL,lst

  



In [ ]:
##### main
res = genetic(L)
fit,LIST = Sort(res[0],res[1])
fit = fit[0]
LIST = LIST[0]
print(LIST)
mat = gen_mat(LIST)
print(mat)
print(fit)

[1, 6, 6, 0, 0, 3, 7, 2]
[[0. 0. 0. 1. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]]
3
