<a href="https://colab.research.google.com/github/ParnianH98/Local-search-on-8-queen/blob/main/hill_climbing_8_queen.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import random

get a filtered-arbitrary initial state of 8-queen from the user

In [ ]:
L = []
for j in range(8):
    a = random.randint(0,7)
    L.append(a)

mat = np.zeros((8,8))
print(L)
print(mat)


[2, 6, 5, 1, 7, 5, 4, 5]
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


generate the board matrix from the entered list

In [ ]:
def gen_mat(List):
  matrix = np.zeros((8,8))
  for i in range(8):
    matrix[List[i]][i] = 1
  return matrix
  

calculate the objective function for a board:
how many queen pairs attack each other

In [ ]:
def objective_cal(lst):
  
  attack = 0
  for i in range(8):
    for j in range(i+1,8):
      if lst[i]==lst[j]:
        attack+=1
      elif (i-j == lst[i]-lst[j]) or (j-i == lst[i]-lst[j]):
        attack+=1

  return attack

    



this function finds the best neighbour for the current state

In [ ]:
def findNeighbour(matrix,lst):
  objVal = objective_cal(lst)

  FNeighbour = matrix.copy()
  lstFNeighbour = lst.copy()

  tempNeighbour = matrix.copy()
  lstTempNeighbour = lst.copy()

  for i in range(8):
    for j in range(8):

      # to work on neighbours, not the matrix itself
      if j != lst[i]:

        # to make a neighbour
        lstTempNeighbour[i] = j
        tempNeighbour[lstTempNeighbour[i]][i] = 1
        tempNeighbour[lst[i]][i] = 0
        tempObjVal = objective_cal(lstTempNeighbour)

        if tempObjVal < objVal:
          objVal = tempObjVal
          FNeighbour = tempNeighbour.copy()
          lstFNeighbour = lstTempNeighbour.copy()

        # to reset variable for the next round
        lstTempNeighbour[i] = lst[i]
        tempNeighbour[lstTempNeighbour[i]][i] = 0
        tempNeighbour[lst[i]][i] = 1


  matrix = FNeighbour.copy()
  lst = lstFNeighbour.copy()

  return matrix,lst


In [ ]:
def hillClimbing(matrix,lst):
  Neighbour = matrix.copy() 
  Nlst = lst.copy()

  for counter in range(500):
    N = findNeighbour(Neighbour,Nlst)
    Neighbour = N[0]
    Nlst = N[1]

    lst = np.array(lst)
    Nlst = np.array(Nlst)

    if ((Nlst == lst).all() and objective_cal(Nlst)==0):
      return Neighbour

    if (objective_cal(Nlst)==objective_cal(lst)):
    # We have stuck in a shoulder! So find another initial state and go on
      i = random.randint(0,7)
      j = random.randint(0,7)
      Nlst[i] = random.randint(0,7)
      Nlst[j] = random.randint(0,7)
      Neighbour = gen_mat(Nlst)
  
  return Neighbour,Nlst

In [ ]:
##### main

mat = gen_mat(L)
m = hillClimbing(mat,L)
mat=[]
L = m[1]
mat = gen_mat(L)
print(mat)


[[0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]]


In [ ]:
print(objective_cal(L))

1
